#!/bin/bash

find . -type f -name '.DS_Store' -delete

BUILD_DATE="$(date '+%Y%m%d')"

TAG="${GIT_COMMIT:-$(git describe --long --dirty --abbrev=10 --tags --always)}-${BUILD_DATE}"

# you must commit changes first
git diff --cached --exit-code || exit 1
git diff --exit-code || exit 2

DOCKER_BUILDKIT=1 docker build --pull -t "${BASE}:${TAG}" .
